- src/main/java/org/apache/maven/plugins/pmd/AbstractPmdViolationCheckMojo.java
- src/test/java/org/apache/maven/plugins/pmd/PmdViolationCheckMojoTest.java
- src/test/resources/unit/default-configuration/pmd-check-failmaxviolation-plugin-config.xml
- src/test/resources/unit/default-configuration/pmd-check-notfailmaxviolation-plugin-config.xml
Add the option to allow users to set the maximum number of violations that can occur before a build fails.
> Add the ability to set the maximum number of allowed violations before a build fails

- pom.xml
- src/it/MPMD-295-JDK13/invoker.properties
- src/it/MPMD-295-JDK13/pom.xml
- src/it/MPMD-295-JDK13/src/main/java/com/mycompany/app/App.java
- src/it/MPMD-295-JDK13/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-295-JDK13/verify.groovy
- src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
Description:
Add a test case that uses Java 13, and update the PMD dependency to 6.18.0 which works with Java 13. This way, the next release of the maven-pmd-plugin will successfully work with Java 13.
the [Apache …
> [MPMD-295] - Maven PMD Plugin fails on Java 13: Unsupported targetJdk value '13'	

- src/main/java/org/apache/maven/plugins/pmd/exec/PmdExecutor.java
Report extension is currently set to match the format, as in "csv", "html". This fails when you specify the format as a fully qualified class name. Since the renderer interface includes a method defaultFileExtension(), we should use this instead to set the file extension.
[INFO] Tests …
> [MPMD-314] PMD report extension not set correctly for custom renderer

- pom.xml
Maven core artifacts should be in provided scope.  While bumped to 3.1.1 in master, maven-pmd-plugin 3.15.0 leaks old asm due to incorrect scope while stating in pom exclusion elsewhere for same leak concern (on maven-embedder).  I believe there are more that should be set to provided but kept this as small as possible to match when it was applied in release 3.15.0.  The original diff shows where issue was introduced [here](https://github.com/apache/maven-pmd-plugin/commit/3ffd4d3762028b1b0a8f714297a21de37d0c5649) in that maven-core was raised up to 3.1.0 and had asm issue at that point.
note: maven-core 3.1.1 does not expose asm issue, just clarifying current release has this issue due to 3.1.0.
> Make maven core provided scope

- pom.xml
Fixes
* https://issues.apache.org/jira/browse/MPMD-330
* https://issues.apache.org/jira/browse/MPMD-331
please …
> [MPMD-330] [MPMD-331] Upgrade Maven Parent to 35 and Require Maven 3.2.5+

- src/site/markdown/releasenotes.md
- src/site/site.xml
JIRA: https://issues.apache.org/jira/browse/MPMD-333 - Add release notes documentation
please ask on the …
> [MPMD-333] - Add release notes documentation

- pom.xml
There are warnings in the build about this.
> Remove vestigial useJava5 parameter

- src/main/java/org/apache/maven/plugins/pmd/CpdViolationCheckMojo.java
- src/main/java/org/apache/maven/plugins/pmd/PmdViolationCheckMojo.java
There are more instances to be fixed but I think these two are the major offenders that break the integration tests.
> [MPMD-369] Make integration tests robust against system encoding

- src/main/java/org/apache/maven/plugins/pmd/AbstractPmdReport.java
- src/main/java/org/apache/maven/plugins/pmd/ExcludeDuplicationsFromFile.java
- src/main/java/org/apache/maven/plugins/pmd/ExcludeViolationsFromFile.java
- src/main/java/org/apache/maven/plugins/pmd/PmdViolationCheckMojo.java
Followup from #120 for @elharo
> [MNG-6829] Replace any StringUtils#isEmpty(String) and #isNotEmpty(String)

- src/it/MPMD-296-rulesetsTargetDirectory/verify.groovy
- src/it/MPMD-323-multi-module-basedir/verify.groovy
- src/it/multi-module/verify.bsh
- src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
- src/test/java/org/apache/maven/plugins/pmd/PmdReportTest.java
https://issues.apache.org/jira/browse/MPMD-371
In version 3.20.0 (without this patch), two PMD rulesets that have the same filename will overwrite each other when staged into the `${project.build.directory}/pmd/rulesets/` directory.
In the following example, the two distinct `pmd-ruleset.xml` files will both be copied as `${project.build.directory}/pmd/rulesets/pmd-ruleset.xml`, so the last copied will overwrite the first: only one of those files will be taken into account.
```xml
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-pmd-plugin</artifactId>
<version>${pmd-maven-plugin.version}</version>
<configuration>
<rulesets>
<ruleset>${project.basedir}/pmd-ruleset.xml</ruleset>
<ruleset>${project-root.basedir}/pmd-ruleset.xml</ruleset>
</rulesets>
</configuration> …
```
> [MPMD-371] Using two ruleset files with same name in different directories

- src/it/MPMD-165/invoker.properties
- src/it/MPMD-182/invoker.properties
- src/it/MPMD-206-sourceDirectories-js/invoker.properties
- src/it/MPMD-219-pmd-processing-error/invoker.properties
- src/it/MPMD-244-logging/invoker.properties
- src/it/MPMD-244-logging/verify.groovy
- src/it/MPMD-258-multiple-executions/invoker.properties
- src/it/MPMD-258-multiple-executions/verify.groovy
- src/it/MPMD-266-typeresolution-aggregated/invoker.properties
- src/it/MPMD-268-deprecated-rules/invoker.properties
- src/it/MPMD-277-multi-module-check/invoker.properties
- src/it/MPMD-283-aggregated-pmd/invoker.properties
- src/it/MPMD-317-auxclasspath-provided/invoker.properties
- src/it/MPMD-317-auxclasspath-provided/verify.groovy
- src/it/MPMD-318-auxclasspath-includeTests/invoker.properties
- src/it/MPMD-318-auxclasspath-includeTests/verify.groovy
- src/it/MPMD-323-multi-module-basedir/invoker.properties
- src/it/MPMD-323-ruleset-basedir-jgitver/invoker.properties
- src/it/MPMD-89-232-typeresolution/invoker.properties
- src/it/empty-rulesets/invoker.properties
> Remove outdated

- src/main/java/org/apache/maven/plugins/pmd/CpdReport.java
- src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
- src/test/java/org/apache/maven/plugins/pmd/AbstractPmdReportTestCase.java
- src/test/java/org/apache/maven/plugins/pmd/CpdReportTest.java
Implement getOutputPath and identify getOutputName as deprecated, as it already is in super-interface MavenReport
> [MPMD-411] Implement getOutputPath and identify getOutputName as deprecated,

- src/test/java/org/apache/maven/plugins/pmd/AbstractPmdReportTestCase.java
Let's take this one file at a time to see if we can isolate the Windows test failures.
> [MPMD-412] clean up unused code

- src/test/java/org/apache/maven/plugins/pmd/CpdReportTest.java
> Avoid catching raw exception

- pom.xml
- src/main/java/org/apache/maven/plugins/pmd/AbstractPmdReport.java
- src/main/java/org/apache/maven/plugins/pmd/AggregatorCpdReport.java
- src/main/java/org/apache/maven/plugins/pmd/AggregatorPmdNoForkReport.java
- src/main/java/org/apache/maven/plugins/pmd/AggregatorPmdReport.java
- src/main/java/org/apache/maven/plugins/pmd/CpdReport.java
- src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
- src/main/java/org/apache/maven/plugins/pmd/exec/CpdExecutor.java
- src/main/java/org/apache/maven/plugins/pmd/exec/CpdRequest.java
- src/main/java/org/apache/maven/plugins/pmd/exec/CpdServiceExecutor.java
- src/main/java/org/apache/maven/plugins/pmd/exec/PmdExecutor.java
- src/main/java/org/apache/maven/plugins/pmd/exec/PmdRequest.java
- src/main/java/org/apache/maven/plugins/pmd/exec/PmdServiceExecutor.java
- src/main/java/org/apache/maven/plugins/pmd/exec/ServiceExecutor.java
- src/test/java/org/apache/maven/plugins/pmd/AbstractPmdReportTestCase.java
Standard mojos and reports have different parent classes, so we need to extract tasks which both will execute.
We cannot use one abstract for both.
> Introduce service executors for CPD, PMD executors

- pom.xml
- src/main/java/org/apache/maven/plugins/pmd/AggregatorPmdNoForkReport.java
- src/main/java/org/apache/maven/plugins/pmd/AggregatorPmdReport.java
- src/main/java/org/apache/maven/plugins/pmd/ConfigurationService.java
- src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
- src/test/java/org/apache/maven/plugins/pmd/AbstractPmdReportTestCase.java
- use resolver API for resolving dependencies
- introduce ConfigurationService as util where we will be able to move the methods needed for preparing configuration for PMDExecutor
> Get rid of maven-artifact-transfer and other legacy stuff

- src/main/java/org/apache/maven/plugins/pmd/AbstractPmdReport.java
- src/main/java/org/apache/maven/plugins/pmd/AbstractPmdViolationCheckMojo.java
- src/main/java/org/apache/maven/plugins/pmd/exec/PmdExecutor.java
Mostly removes IDE generated boilerplate that only occupies vertical screen space
> Clean up some Javadoc comments

- src/site/apt/examples/violation-exclusions.apt.vm
> Documentation: Excludes should be placed in pluginManagement (#637)

- pom.xml
It will allow declaring a newer version of Maven dependencies in the project.
> Use constant 3.6.3 in prerequisites/maven as minimal Maven version

- pom.xml
- src/it/MPMD-163/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-270-325-JDK11/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-280-JDK12/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-295-JDK13/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-302-JDK14/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-302-JDK15/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-312-JDK16/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-312-JDK17/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-332-JDK18/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-348-JDK19/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-365-JDK20/src/main/java/com/mycompany/app/Foo.java
- src/it/MPMD-379-JDK21/src/main/java/com/mycompany/app/Foo.java
- src/it/empty-rulesets/src/main/java/com/mycompany/app/Foo.java
- src/main/resources/rulesets/java/maven-pmd-plugin-default.xml
- src/main/resources/rulesets/maven.xml
- src/site/apt/examples/usingRuleSets.apt.vm
Fixes tests that broke while updating PMD from version 7.16.0 to version 7.17.0.
- UselessOperationOnImmutable was replaced with UselessPureMethodCall
- Update test fixtures because UnusedFormalParameter now ignores public constructors
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
the [Apache …
> Fix #657 broken tests after upgrade to PMD 7.17.0
