apache/maven-pmd-plugin

pom.xml, src/it/MPMD-266-typeresolution-aggregated/invoker.properties, src/it/MPMD-266-typeresolution-aggregated/pom.xml
Signed-off-by: olivier lamy <olamy@apache.org>
=> upgrade site plugin version 3.7.1 and mpir 3.0.0 fix failing ITs with last maven 3.5.4

pom.xml
Signed-off-by: olivier lamy <olamy@apache.org>
=> [MPMD-271] upgrade PMD 6.8.0

src/it/mpmd-168-empty-report/verify.groovy, src/main/java/org/apache/maven/plugins/pmd/PmdReportGenerator.java, src/main/resources/pmd-report.properties, src/main/resources/pmd-report_de.properties, src/test/java/org/apache/maven/plugins/pmd/CpdReportTest.java, src/test/java/org/apache/maven/plugins/pmd/PmdReportTest.java
https://issues.apache.org/jira/browse/MPMD-282
=> [MPMD-282] Add rule name to HTML report

src/it/MPMD-266-typeresolution-aggregated/module-b/pom.xml, src/it/MPMD-266-typeresolution-aggregated/ruleset.xml, src/it/MPMD-277-multi-module-check/invoker.properties, src/it/MPMD-277-multi-module-check/module-a/pom.xml, src/it/MPMD-277-multi-module-check/module-a/src/main/java/module/a/IModuleA.java, src/it/MPMD-277-multi-module-check/module-a/src/main/java/module/a/ModuleA.java, src/it/MPMD-277-multi-module-check/module-b/pom.xml, src/it/MPMD-277-multi-module-check/module-b/src/main/java/module/b/ModuleB.java, src/it/MPMD-277-multi-module-check/pom.xml, src/it/MPMD-277-multi-module-check/ruleset.xml, src/it/MPMD-277-multi-module-check/verify.groovy, src/main/java/org/apache/maven/plugins/pmd/PmdReport.java, src/site/fml/faq.fml
https://issues.apache.org/jira/browse/MPMD-277
=> [MPMD-277] Plugin tries to download local submodules from repo

src/main/java/org/apache/maven/plugins/pmd/AbstractPmdViolationCheckMojo.java
only for checks, for reports already done
To make clear that you license …
=> [MPMD-269] - Display PMD version that is being used

pom.xml
https://issues.apache.org/jira/browse/MPMD-291
=> [MPMD-291] Upgrade to PMD 6.17.0

src/main/resources/rulesets/java/maven-pmd-plugin-default.xml, src/main/resources/rulesets/maven.xml, src/site/apt/examples/multi-module-config.apt.vm, src/site/apt/examples/usingRuleSets.apt.vm
Follow-up to https://github.com/pmd/pmd/commit/04b0859fb2
(pmd_releases/6.3.0-123-g04b0859fb2)
please ask on …
=> (doc) Update references to PMD documentation

src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
=> [MPMD-297] - Classloader not being closed after PMD run

src/main/java/org/apache/maven/plugins/pmd/AbstractPmdReport.java
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> (doc) Add missing @Override

src/main/java/org/apache/maven/plugins/pmd/AbstractPmdViolationCheckMojo.java, src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> (doc) Merge the same exception handlers

pom.xml
=> add undeclared but used SLF4J dependency

src/main/java/org/apache/maven/plugins/pmd/exec/PmdExecutor.java
@michael-o a rare case where try with resources doesn't work due to a cast to Closeable
=> replace deprecated method

src/site/apt/examples/violation-exclusions.apt.vm
Improve the documentation around `exclude-cpd.properties` file formatting
https://issues.apache.org/jira/browse/MPMD-311
=> [MPMD-311] - Improve excludeFileFromFailure docs

src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
https://issues.apache.org/jira/browse/MPMD-318
In this PR I address the issue with auxiliary classpath that is being created in PmdReport.java. In case if 'includeTests' parameter is set to `true`, only test dependencies jars and test compiled classes are being added to the classpath, resulting in NoClassDefFoundErrors 
be performed …
=> [MPMD-318] Fix the aux classpath when includeTests is set to true

.github/workflows/maven-verify.yml
=> [MPMD-328] Shared Github Actions

src/main/java/org/apache/maven/plugins/pmd/PmdReport.java, src/test/java/org/apache/maven/plugins/pmd/PmdReportTest.java, src/test/resources/unit/default-configuration/pmd-report-resolve-rulesets.xml
Fixes https://issues.apache.org/jira/browse/MPMD-324
To make clear that you …
=> [MPMD-324] Ruleset URLs have hyphen replaced with forwardslash

src/it/MPMD-323-multi-module-basedir/config/pmd/ruleset.xml, src/it/MPMD-323-multi-module-basedir/invoker.properties, src/it/MPMD-323-multi-module-basedir/module-a/pom.xml, src/it/MPMD-323-multi-module-basedir/module-a/src/main/java/module/a/ModuleA.java, src/it/MPMD-323-multi-module-basedir/module-b/pom.xml, src/it/MPMD-323-multi-module-basedir/module-b/src/main/java/module/b/ModuleB.java, src/it/MPMD-323-multi-module-basedir/pom.xml, src/it/MPMD-323-multi-module-basedir/verify.groovy, src/it/MPMD-323-ruleset-basedir-jgitver/.mvn/extensions.xml, src/it/MPMD-323-ruleset-basedir-jgitver/config/pmd/ruleset.xml, src/it/MPMD-323-ruleset-basedir-jgitver/invoker.properties, src/it/MPMD-323-ruleset-basedir-jgitver/pom.xml, src/it/MPMD-323-ruleset-basedir-jgitver/src/main/java/sample/Sample.java, src/it/MPMD-323-ruleset-basedir-jgitver/verify.groovy, src/main/java/org/apache/maven/plugins/pmd/PmdReport.java, src/test/java/org/apache/maven/plugins/pmd/AbstractPmdReportTest.java, src/test/java/org/apache/maven/plugins/pmd/CpdViolationCheckMojoTest.java, src/test/java/org/apache/maven/plugins/pmd/PmdViolationCheckMojoTest.java
location
https://issues.apache.org/jira/browse/MPMD-323
To make clear that …
=> [MPMD-323] ResourceManager should use project base dir instead of pom

src/it/MPMD-332-JDK18/invoker.properties, src/it/MPMD-332-JDK18/pom.xml, src/it/MPMD-332-JDK18/src/main/java/com/mycompany/app/App.java, src/it/MPMD-332-JDK18/src/main/java/com/mycompany/app/Foo.java, src/it/MPMD-332-JDK18/verify.groovy, src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
Jira: https://issues.apache.org/jira/browse/MPMD-332
This PR adds an IT for Java 18 and updates the doc for parameter `targetJdk`.
[Individual Contributor License …
=> [MPMD-332] - Support Java 18

pom.xml, src/site/markdown/releasenotes.md
Jira: https://issues.apache.org/jira/browse/MPMD-337
To make clear that you …
=> [MPMD-337] - Upgrade Maven Parent to 36

src/it/MPMD-335-aggregate-classpath-repositories/invoker.properties, src/it/MPMD-335-aggregate-classpath-repositories/mpmd335-module1/pom.xml, src/it/MPMD-335-aggregate-classpath-repositories/mpmd335-module1/src/main/java/org/example/Foo.java, src/it/MPMD-335-aggregate-classpath-repositories/pom.xml, src/it/MPMD-335-aggregate-classpath-repositories/private-repo/org/apache/maven/plugins/pmd/it/mpmd335-dependency1/1.0.0-SNAPSHOT/mpmd335-dependency1-1.0.0-SNAPSHOT.pom, src/it/MPMD-335-aggregate-classpath-repositories/verify.groovy, src/main/java/org/apache/maven/plugins/pmd/PmdReport.java
https://issues.apache.org/jira/browse/MPMD-335
To make clear that you …
=> [MPMD-335] - Aggregate mode doesn't use additional repositories

src/it/MPMD-270-325-JDK11/verify.groovy, src/it/MPMD-280-JDK12/verify.groovy, src/it/MPMD-295-JDK13/verify.groovy, src/it/MPMD-302-JDK14/verify.groovy, src/it/MPMD-302-JDK15/verify.groovy, src/it/MPMD-312-JDK16/verify.groovy, src/it/MPMD-312-JDK17/verify.groovy, src/it/MPMD-332-JDK18/verify.groovy, src/it/MPMD-348-JDK19/verify.groovy, src/it/MPMD-365-JDK20/verify.groovy
=> [MPMD-367] don't fail on unrelated warnings

src/site/apt/index.apt.vm
=> Typo: fill --> file

src/main/java/org/apache/maven/plugins/pmd/exec/CpdExecutor.java, src/main/java/org/apache/maven/plugins/pmd/exec/CpdReportConsumer.java, src/test/java/org/apache/maven/plugins/pmd/CpdReportTest.java, src/test/java/org/apache/maven/plugins/pmd/exec/ExecutorTest.java, src/test/resources/unit/CpdReportTest/with-cpd-errors/pom.xml, src/test/resources/unit/CpdReportTest/with-cpd-errors/src/main/java/sample/BadFile.java, src/test/resources/unit/invalid-format/cpd-invalid-format-plugin-config.xml
https://issues.apache.org/jira/browse/MPMD-395
Refs https://github.com/apache/maven-pmd-plugin/pull/144#issuecomment-2094372771
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) …
=> [MPMD-395] Build doesn't fail for invalid CPD format

pom.xml
=> [MPMD-397] Upgrade to Maven 3.6.3

src/site/xdoc/download.xml.vm
=> [MPMD-398] Refresh download page

src/site/markdown/releasenotes.md
=> [MPMD-405] Update release notes for 3.25.0

src/main/java/org/apache/maven/plugins/pmd/PmdViolationCheckMojo.java
=> Fix doubled the

pom.xml
=> Upgrade to PMD 7.12

.github/workflows/release-drafter.yml
=> Use shared release-drafter action

src/site/site.xml
=> Update site descriptor to 2.0

src/main/java/org/apache/maven/plugins/pmd/exec/CpdReportConsumer.java, src/test/java/org/apache/maven/plugins/pmd/CpdReportTest.java
=> [MPMD-412] More specific catch blocks
